/*  
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2.1
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


#include <netinet/in.h>

#include <fcntl.h>
#include <unistd.h> 
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <sys/types.h>
#include <inttypes.h>
#include <assert.h>

#define TS_PACKET_SIZE 188
#define MAX_SECTION_LEN 4096
#define MAX_PID 8192
#define MAX_TABLE_ID_EXT 9999
#define SECTION_HEADER_SIZE 3

unsigned char section[MAX_SECTION_LEN];

void dump_section() {
	int sec_len;

	memcpy( &sec_len, section + 1, 2 );
	sec_len = ntohs( sec_len );
	sec_len = sec_len & 0x0fff;

	if ( sec_len + 3 != write( STDOUT_FILENO, section, sec_len + 3))
	{
		perror("write");
	}
}

int get_section(int fd_sec, int *table_id_ext) {
	unsigned char sec_header[3];
	int r;
	int sec_len;
	
	r = read( fd_sec, sec_header, 3 );
	if ( r != 3 )
	{
		return -1;
	}

	memcpy( &sec_len, sec_header + 1, 2 );
	sec_len = ntohs( sec_len );
	sec_len = sec_len & 0x0fff;

	memcpy( section, sec_header, 3 );
	r = read( fd_sec, section + 3, sec_len );
	if ( r != sec_len )
	{
		return -1;
	}

	memcpy( table_id_ext, section + 3, 2 );	
	*table_id_ext = ntohs( *table_id_ext );

	return 0;
}

int main(int argc, char *argv[])
{
	int fd_sec;			/* File descriptor of ts file */
	int table_id_ext;
    int ext;
    int st;

	/* Open ts file */
	if (argc >= 3) {
		fd_sec = open( argv[1], O_RDONLY );
        table_id_ext = atoi( argv[2] );
	} else {
		fprintf(stderr, "Usage: 'subtable filename.sec table_id_ext'\n");
		fprintf(stderr, "the tool dumps subtable from a section dump generated by ts2sec.\n");
		return 2;
	}
	if (fd_sec < 0) {
		fprintf(stderr, "Can't find file %s\n", argv[1]);
		return 2;
	}
	
	while( 1 ) 
    {
        unsigned char cur_sec;
        unsigned char last_sec;

		st = get_section( fd_sec, &ext );
		if ( st != 0 )
		{
			fprintf(stderr, "File format error. %s\n", argv[1]);
			break;
		}

		if ( table_id_ext == ext )
		{
			dump_section();
		}

        cur_sec = section[6];
        last_sec = section[7];
        if ( cur_sec == last_sec )
        {
            break;
        }
	}

	close( fd_sec );

	return 0;
}

